ALTER TABLE client
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP NULL DEFAULT NULL,
    ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
